### ISSUE TITLE
Add animation on scroll effect for different items

### ISSUE THREAD

**Issue by Signior-X** [E-Cell-IITMandi/e-cell-iitmandi.github.io#17]
You might have observed that on certain websites. As you scroll down, the item pops out. It remains invisible until user reaches that point. We plan to implement such feature.

**Comment by mindninjaX** [comment]
Hi @Signior-X! Well, this sounds fun ✨ I would like to work on this :D

**Comment by Signior-X** [comment]
Sure go ahead!

**Comment by mindninjaX** [comment]
Thanks! I'll start working on this right away 🚀
