### ISSUE TITLE
Create a Team page

### ISSUE THREAD

**Issue by Signior-X** [E-Cell-IITMandi/e-cell-iitmandi.github.io#5]
Team page will be different. This issue has to be divided into parts that everyone can take small small parts and solve it.

**Comment by Signior-X** [comment]
Basic layout ready. Design the way you want to.

**Comment by Signior-X** [comment]
So, in this issue you need to design a card. Just design a single card for showing the team members.
Current team is https://ecell.iitmandi.co.in/team.html, however don't make the whole page. `team.html` is the file that needs to be edited, `team.css` must contain the CSS. 


First only design a basic card. 
And then we will add all the cards dynamically will be another issue related to it.

**Comment by lavish2210** [comment]
I will be working on that.

**Comment by Signior-X** [comment]
@lavish2210 We just merged the PR. So, now our aim is to read the data from `data.team.yaml` and create the html using Javascript dynamically using this file. Give it a try.
