### ISSUE TITLE
Create About left column

### ISSUE THREAD

**Issue by Signior-X** [E-Cell-IITMandi/e-cell-iitmandi.github.io#8]
![image](https://user-images.githubusercontent.com/56730716/122665692-51245f00-d1c6-11eb-85a3-c6259449110c.png)
Screenshot taken from https://clickup.com/careers

Your task is to make only the **left column** as shown in the screenshot. The code needs to be added at index.html like 166 where 
```html
<!-- Add Column 1 here / TODO -->
Column 1
```
is written.

**Comment by Ritam727** [comment]
Would be working on it
