### ISSUE TITLE
Create About right column

### ISSUE THREAD

**Issue by Signior-X** [E-Cell-IITMandi/e-cell-iitmandi.github.io#9]
![image](https://user-images.githubusercontent.com/56730716/122665692-51245f00-d1c6-11eb-85a3-c6259449110c.png)
Screenshot taken from https://clickup.com/careers

Your task is to make only the **right column** as shown in the screenshot. The code needs to be added at `index.html` line 170 where 
```html
<!-- Add Column 2 here / TODO -->
Column 2
```
is written.

**Comment by yuvraj-aseri** [comment]
working on it

**Comment by Signior-X** [comment]
#10, #11 both are good.
